"""Shared types for ReelsEdits services.

The Editing Blueprint is the only interface between analysis and rendering, so
it lives here rather than in any one service. Everything upstream produces one;
everything downstream is a pure function of one.

See docs/06-blueprint-spec.md.
"""

from __future__ import annotations

from .blueprint import (
    CONFIDENCE_FLOOR,
    EBP_VERSION,
    Assignment,
    AudioSection,
    AudioTrack,
    Blueprint,
    Canvas,
    CaptionTrack,
    Compromise,
    ConfidenceBreakdown,
    Constraints,
    Cut,
    Degradation,
    EffectInstance,
    EnergyCurve,
    Grade,
    GradeMatchTarget,
    GradeParams,
    HslBand,
    Impact,
    Keyframe,
    MotionTrack,
    MusicBinding,
    PacingProfile,
    PaletteColor,
    Position,
    Provenance,
    ReframeTrack,
    SfxEvent,
    Slot,
    SlotGrade,
    SlotRequirements,
    SpeedTrack,
    SplitTone,
    StyleProfile,
    TextAnimation,
    TextObject,
    TextStyle,
    Transition,
)
from .enums import (
    CameraHeight,
    CameraMotion,
    CaptionMode,
    Composition,
    CompromiseKind,
    CutMode,
    Easing,
    EffectType,
    FontFamily,
    MusicStrategy,
    NarrativeRole,
    SectionKind,
    ShotScale,
    SpeedMode,
    SubjectClass,
    TextAnimationKind,
    TransitionType,
)

__version__ = "0.1.0"

__all__ = [
    "CONFIDENCE_FLOOR",
    "EBP_VERSION",
    # blueprint
    "Assignment",
    "AudioSection",
    "AudioTrack",
    "Blueprint",
    # enums
    "CameraHeight",
    "CameraMotion",
    "Canvas",
    "CaptionMode",
    "CaptionTrack",
    "Composition",
    "Compromise",
    "CompromiseKind",
    "ConfidenceBreakdown",
    "Constraints",
    "Cut",
    "CutMode",
    "Degradation",
    "Easing",
    "EffectInstance",
    "EffectType",
    "EnergyCurve",
    "FontFamily",
    "Grade",
    "GradeMatchTarget",
    "GradeParams",
    "HslBand",
    "Impact",
    "Keyframe",
    "MotionTrack",
    "MusicBinding",
    "MusicStrategy",
    "NarrativeRole",
    "PacingProfile",
    "PaletteColor",
    "Position",
    "Provenance",
    "ReframeTrack",
    "SectionKind",
    "SfxEvent",
    "ShotScale",
    "Slot",
    "SlotGrade",
    "SlotRequirements",
    "SpeedMode",
    "SpeedTrack",
    "SplitTone",
    "StyleProfile",
    "SubjectClass",
    "TextAnimation",
    "TextAnimationKind",
    "TextObject",
    "TextStyle",
    "Transition",
    "TransitionType",
    "__version__",
]
